version: "3.8"
services:
  dog_breed_service-app:
    restart: always
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
    environment:
      MYSQL_DATABASE: dbtest
      MYSQL_USER: lucas
      MYSQL_PASSWORD: lucas
      MYSQL_ROOT_PASSWORD: lucas
  mysqldb:
    platform: linux/x86_64
    restart: always
    container_name: mysqldb
    image: "mysql:5.7"
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: dbtest
      MYSQL_USER: lucas
      MYSQL_PASSWORD: lucas
      MYSQL_ROOT_PASSWORD: lucas
